/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/message': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * メッセージ取得
     * @description クエリパラメータのメッセージをエコーします
     */
    get: {
      parameters: {
        query?: {
          message?: string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              /** @example Hello, Lydos! */
              message: string
              /** @example 2026-01-27T12:00:00.000Z */
              timestamp: string
            }
          }
        }
      }
    }
    put?: never
    /**
     * メッセージエコー
     * @description 送信されたメッセージをそのまま返します
     */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: {
        content: {
          'application/json': {
            /** @example Hello, Lydos! */
            message: string
          }
        }
      }
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              /** @example Hello, Lydos! */
              message: string
              /** @example 2026-01-27T12:00:00.000Z */
              timestamp: string
            }
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: never
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export type operations = Record<string, never>
